import React from 'react';
import { ScrollView, StyleSheet, View, Text, SafeAreaView } from 'react-native';
import DisplayRepetidoras from '../components/DisplayRepetidoras';
import SelecionarCidade from '../components/SelecionarCidade'
import estilo from '../components/estilo';
import Container from "../components/Container";

export default function ConsultaRep() {
//const ConsultaRep = () => {

  const [cidade, setCidade] = React.useState("")

   const cidades = [
    {key:'Acari', value:'Acari'},
    {key:'Adrianópolis', value:'Adrianópolis'},
    {key:'Águas da Prata', value:'Águas da Prata'},
    {key:'Alegrete', value:'Alegrete'},
    {key:'Almirante Tamandaré', value:'Almirante Tamandaré'},
    {key:'Altinópolis', value:'Altinópolis'},
    {key:'Americana', value:'Americana'},
    {key:'Amparo', value:'Amparo'},
    {key:'Ananindeua', value:'Ananindeua'},
    {key:'Anápolis', value:'Anápolis'},
    {key:'Andirá', value:'Andirá'},
    {key:'Angélica', value:'Angélica'},
    {key:'Angra dos Reis', value:'Angra dos Reis'},
    {key:'Apiaí', value:'Apiaí'},
    {key:'Apucarana', value:'Apucarana'},
    {key:'Aquidauana', value:'Aquidauana'},
    {key:'Aracaju', value:'Aracaju'},
    {key:'Araranguá', value:'Araranguá'},
    {key:'Araraquara', value:'Araraquara'},
    {key:'Araras', value:'Araras'},
    {key:'Araxá', value:'Araxá'},
    {key:'Artur Nogueira', value:'Artur Nogueira'},
    {key:'Astolfo Dutra', value:'Astolfo Dutra'},
    {key:'Aurora', value:'Aurora'},
    {key:'Bacabal', value:'Bacabal'},
    {key:'Bagé', value:'Bagé'},
    {key:'Balsa Nova', value:'Balsa Nova'},
    {key:'Barbacena', value:'Barbacena'},
    {key:'Barra do Piraí', value:'Barra do Piraí'},
    {key:'Barra dos Coqueiros', value:'Barra dos Coqueiros'},
    {key:'Barra Mansa', value:'Barra Mansa'},
    {key:'Barroso', value:'Barroso'},
    {key:'Batalha', value:'Batalha'},
    {key:'Bauru', value:'Bauru'},
    {key:'Belém', value:'Belém'},
    {key:'Belo Horizonte', value:'Belo Horizonte'},
    {key:'Bento Gonçalves', value:'Bento Gonçalves'},
    {key:'Birigui', value:'Birigui'},
    {key:'Blumenau', value:'Blumenau'},
    {key:'Boa Vista', value:'Boa Vista'},
    {key:'Bom Jardim', value:'Bom Jardim'},
    {key:'Bom Jesus do Itabapoana', value:'Bom Jesus do Itabapoana'},
    {key:'Bom Jesus do Norte', value:'Bom Jesus do Norte'},
    {key:'Bom Sucesso', value:'Bom Sucesso'},
    {key:'Botucatu', value:'Botucatu'},
    {key:'Bragança', value:'Bragança'},
    {key:'Brasília', value:'Brasília'},
    {key:'Brusque', value:'Brusque'},
    {key:'Bueno Brandão', value:'Bueno Brandão'},
    {key:'Cabo Frio', value:'Cabo Frio'},
    {key:'Cabreúva', value:'Cabreúva'},
    {key:'Caçador', value:'Caçador'},
    {key:'Caçapava do Sul', value:'Caçapava do Sul'},
    {key:'Cachoeiro de Itapemirim', value:'Cachoeiro de Itapemirim'},
    {key:'Cachoeiro do Itapemirim', value:'Cachoeiro do Itapemirim'},
    {key:'Caeté', value:'Caeté'},
    {key:'Caicó', value:'Caicó'},
    {key:'Cajati', value:'Cajati'},
    {key:'Caldas Novas', value:'Caldas Novas'},
    {key:'Camaçari', value:'Camaçari'},
    {key:'Camaquã', value:'Camaquã'},
    {key:'Camaragibe', value:'Camaragibe'},
    {key:'Campina Grande do Sul', value:'Campina Grande do Sul'},
    {key:'Campina Grande', value:'Campina Grande'},
    {key:'Campinas', value:'Campinas'},
    {key:'Campo Alegre', value:'Campo Alegre'},
    {key:'Campo Belo', value:'Campo Belo'},
    {key:'Campo Grande', value:'Campo Grande'},
    {key:'Campo Mourão', value:'Campo Mourão'},
    {key:'Campo Redondo', value:'Campo Redondo'},
    {key:'Campos dos Goytacazes', value:'Campos dos Goytacazes'},
    {key:'Candelária', value:'Candelária'},
    {key:'Canguçu', value:'Canguçu'},
    {key:'Canoas', value:'Canoas'},
    {key:'Capela', value:'Capela'},
    {key:'Carambeí', value:'Carambeí'},
    {key:'Carangola', value:'Carangola'},
    {key:'Caratinga', value:'Caratinga'},
    {key:'Carmo da Mata', value:'Carmo da Mata'},
    {key:'Carmo', value:'Carmo'},
    {key:'Cascavel', value:'Cascavel'},
    {key:'Casimiro de Abreu', value:'Casimiro de Abreu'},
    {key:'Castanhal', value:'Castanhal'},
    {key:'Catalão', value:'Catalão'},
    {key:'Caxias do Sul', value:'Caxias do Sul'},
    {key:'Cerqueira César', value:'Cerqueira César'},
    {key:'Cerro Corá', value:'Cerro Corá'},
    {key:'Chapeco', value:'Chapeco'},
    {key:'Cianorte', value:'Cianorte'},
    {key:'Colatina', value:'Colatina'},
    {key:'Colombo', value:'Colombo'},
    {key:'Conceição do Coité', value:'Conceição do Coité'},
    {key:'Concórdia', value:'Concórdia'},
    {key:'Conde', value:'Conde'},
    {key:'Contagem', value:'Contagem'},
    {key:'Cornélio Procópio', value:'Cornélio Procópio'},
    {key:'Córrego do Bom Jesus', value:'Córrego do Bom Jesus'},
    {key:'Correia Pinto', value:'Correia Pinto'},
    {key:'Corumbá', value:'Corumbá'},
    {key:'Cosmopolis', value:'Cosmopolis'},
    {key:'Criciúma', value:'Criciúma'},
    {key:'Cristalina', value:'Cristalina'},
    {key:'Cubatão', value:'Cubatão'},
    {key:'Cuiabá', value:'Cuiabá'},
    {key:'Cuité', value:'Cuité'},
    {key:'Curitiba', value:'Curitiba'},
    {key:'Curitibanos', value:'Curitibanos'},
    {key:'Divinópolis', value:'Divinópolis'},
    {key:'Dois Vizinhos', value:'Dois Vizinhos'},
    {key:'Domingos Martins', value:'Domingos Martins'},
    {key:'Dourados', value:'Dourados'},
    {key:'Dracena', value:'Dracena'},
    {key:'Erechim', value:'Erechim'},
    {key:'Escada', value:'Escada'},
    {key:'Espírito Santo do Pinhal', value:'Espírito Santo do Pinhal'},
    {key:'Fagundes', value:'Fagundes'},
    {key:'Farroupilha', value:'Farroupilha'},
    {key:'Fartura', value:'Fartura'},
    {key:'Feira de Santana', value:'Feira de Santana'},
    {key:'Flores da Cunha', value:'Flores da Cunha'},
    {key:'Flores de Goiás', value:'Flores de Goiás'},
    {key:'Florianopolis', value:'Florianopolis'},
    {key:'Flórida Paulista', value:'Flórida Paulista'},
    {key:'Formiga', value:'Formiga'},
    {key:'Forquilha', value:'Forquilha'},
    {key:'Fortaleza', value:'Fortaleza'},
    {key:'Foz do Iguaçu', value:'Foz do Iguaçu'},
    {key:'Francisco Beltrão', value:'Francisco Beltrão'},
    {key:'Garanhuns', value:'Garanhuns'},
    {key:'Garuva', value:'Garuva'},
    {key:'Goiânia', value:'Goiânia'},
    {key:'Goiatuba', value:'Goiatuba'},
    {key:'Governador Celso Ramos', value:'Governador Celso Ramos'},
    {key:'Governador Valadares', value:'Governador Valadares'},
    {key:'Gramado', value:'Gramado'},
    {key:'Guaçuí', value:'Guaçuí'},
    {key:'Guapé', value:'Guapé'},
    {key:'Guapimirim', value:'Guapimirim'},
    {key:'Guarabira', value:'Guarabira'},
    {key:'Guaramiranga', value:'Guaramiranga'},
    {key:'Guarapuava', value:'Guarapuava'},
    {key:'Guaratinguetá', value:'Guaratinguetá'},
    {key:'Guaratuba', value:'Guaratuba'},
    {key:'Herval', value:'Herval'},
    {key:'Ibirubá', value:'Ibirubá'},
    {key:'Iconha', value:'Iconha'},
    {key:'Igrejinha', value:'Igrejinha'},
    {key:'Iguatu', value:'Iguatu'},
    {key:'Ijuí', value:'Ijuí'},
    {key:'Imbituba', value:'Imbituba'},
    {key:'Inácio Martins', value:'Inácio Martins'},
    {key:'Indaiatuba', value:'Indaiatuba'},
    {key:'Iomerê', value:'Iomerê'},
    {key:'Ipanema', value:'Ipanema'},
    {key:'Ipatinga', value:'Ipatinga'},
    {key:'Ipaussu', value:'Ipaussu'},
    {key:'Iporã do Oeste', value:'Iporã do Oeste'},
    {key:'Ipuiúna', value:'Ipuiúna'},
    {key:'Irati', value:'Irati'},
    {key:'Itabaiana', value:'Itabaiana'},
    {key:'Itabaianinha', value:'Itabaianinha'},
    {key:'Itabirito', value:'Itabirito'},
    {key:'Itaiópolis', value:'Itaiópolis'},
    {key:'Itajaí', value:'Itajaí'},
    {key:'Itajubá', value:'Itajubá'},
    {key:'Itapecerica da Serra', value:'Itapecerica da Serra'},
    {key:'Itaperuna', value:'Itaperuna'},
    {key:'Itapeva', value:'Itapeva'},
    {key:'Itapevi', value:'Itapevi'},
    {key:'Itatinga', value:'Itatinga'},
    {key:'Itaúna', value:'Itaúna'},
    {key:'Itumbiara', value:'Itumbiara'},
    {key:'Jaboatão dos Guararapes', value:'Jaboatão dos Guararapes'},
    {key:'Jaboticabal', value:'Jaboticabal'},
    {key:'Jaboticatubas', value:'Jaboticatubas'},
    {key:'Jacutinga', value:'Jacutinga'},
    {key:'Jaguari', value:'Jaguari'},
    {key:'Jandaia', value:'Jandaia'},
    {key:'Jaraguá do Sul', value:'Jaraguá do Sul'},
    {key:'Jaú', value:'Jaú'},
    {key:'Joaçaba', value:'Joaçaba'},
    {key:'Joanópolis', value:'Joanópolis'},
    {key:'João Câmara', value:'João Câmara'},
    {key:'João Neiva', value:'João Neiva'},
    {key:'João Pessoa', value:'João Pessoa'},
    {key:'Joinville', value:'Joinville'},
    {key:'Juazeiro do Norte', value:'Juazeiro do Norte'},
    {key:'Juiz de Fora', value:'Juiz de Fora'},
    {key:'Jundiaí', value:'Jundiaí'},
    {key:'Laguna', value:'Laguna'},
    {key:'Lambari', value:'Lambari'},
    {key:'Lavras', value:'Lavras'},
    {key:'Leopoldina', value:'Leopoldina'},
    {key:'Limeira', value:'Limeira'},
    {key:'Lindoeste', value:'Lindoeste'},
    {key:'Lins', value:'Lins'},
    {key:'Londrina', value:'Londrina'},
    {key:'Macaé', value:'Macaé'},
    {key:'Macapá', value:'Macapá'},
    {key:'Macaparana', value:'Macaparana'},
    {key:'Mafra', value:'Mafra'},
    {key:'Mairiporã', value:'Mairiporã'},
    {key:'Mamborê', value:'Mamborê'},
    {key:'Manaus', value:'Manaus'},
    {key:'Mandaguari', value:'Mandaguari'},
    {key:'Maracaju', value:'Maracaju'},
    {key:'Maranguape', value:'Maranguape'},
    {key:'Mariana', value:'Mariana'},
    {key:'Maricá', value:'Maricá'},
    {key:'Marília', value:'Marília'},
    {key:'Maringá', value:'Maringá'},
    {key:'Martinho Campos', value:'Martinho Campos'},
    {key:'Martins', value:'Martins'},
    {key:'Mateus Leme', value:'Mateus Leme'},
    {key:'Maturéia', value:'Maturéia'},
    {key:'Matutina', value:'Matutina'},
    {key:'Mauá', value:'Mauá'},
    {key:'Medianeira', value:'Medianeira'},
    {key:'Meruoca', value:'Meruoca'},
    {key:'Miguel Pereira', value:'Miguel Pereira'},
    {key:'Mimoso do Sul', value:'Mimoso do Sul'},
    {key:'Miraí', value:'Miraí'},
    {key:'Mirim Doce', value:'Mirim Doce'},
    {key:'Mogi das Cruzes', value:'Mogi das Cruzes'},
    {key:'Mogi Guaçu', value:'Mogi Guaçu'},
    {key:'Monte Sião', value:'Monte Sião'},
    {key:'Morretes', value:'Morretes'},
    {key:'Morungaba', value:'Morungaba'},
    {key:'Mossoró', value:'Mossoró'},
    {key:'Natal', value:'Natal'},
    {key:'Natércia', value:'Natércia'},
    {key:'Nazaré Paulista', value:'Nazaré Paulista'},
    {key:'Neves Paulista', value:'Neves Paulista'},
    {key:'Nilópolis', value:'Nilópolis'},
    {key:'Niterói', value:'Niterói'},
    {key:'Nossa Senhora do Socorro', value:'Nossa Senhora do Socorro'},
    {key:'Nova Alvorada do Sul', value:'Nova Alvorada do Sul'},
    {key:'Nova Esperança do Sudoeste', value:'Nova Esperança do Sudoeste'},
    {key:'Nova Esperança', value:'Nova Esperança'},
    {key:'Nova Friburgo', value:'Nova Friburgo'},
    {key:'Nova Lima', value:'Nova Lima'},
    {key:'Nova Trento', value:'Nova Trento'},
    {key:'Óbidos', value:'Óbidos'},
    {key:'Olímpia', value:'Olímpia'},
    {key:'Olinda', value:'Olinda'},
    {key:'Oliveira', value:'Oliveira'},
    {key:'Onça de Pitangui', value:'Onça de Pitangui'},
    {key:'Orós', value:'Orós'},
    {key:'Ortigueira', value:'Ortigueira'},
    {key:'Osório', value:'Osório'},
    {key:'Ouro Branco', value:'Ouro Branco'},
    {key:'Ouro Preto', value:'Ouro Preto'},
    {key:'Palestina de Goiás', value:'Palestina de Goiás'},
    {key:'Palmas', value:'Palmas'},
    {key:'Pará de Minas', value:'Pará de Minas'},
    {key:'Paracatu', value:'Paracatu'},
    {key:'Paraguaçu', value:'Paraguaçu'},
    {key:'Paraibuna', value:'Paraibuna'},
    {key:'Paraisópolis', value:'Paraisópolis'},
    {key:'Paranavaí', value:'Paranavaí'},
    {key:'Paraty', value:'Paraty'},
    {key:'Pardinho', value:'Pardinho'},
    {key:'Parnaíba', value:'Parnaíba'},
    {key:'Patrocínio', value:'Patrocínio'},
    {key:'Paty do Alferes', value:'Paty do Alferes'},
    {key:'Paulistana', value:'Paulistana'},
    {key:'Pedro II', value:'Pedro II'},
    {key:'Pelotas', value:'Pelotas'},
    {key:'Pescaria Brava', value:'Pescaria Brava'},
    {key:'Petrópolis', value:'Petrópolis'},
    {key:'Picos', value:'Picos'},
    {key:'Piedade', value:'Piedade'},
    {key:'Pindamonhangaba', value:'Pindamonhangaba'},
    {key:'Piquete', value:'Piquete'},
    {key:'Piracicaba', value:'Piracicaba'},
    {key:'Piraí do Sul', value:'Piraí do Sul'},
    {key:'Piraju', value:'Piraju'},
    {key:'Pirapora', value:'Pirapora'},
    {key:'Piripiri', value:'Piripiri'},
    {key:'Pitanga', value:'Pitanga'},
    {key:'Piumhi', value:'Piumhi'},
    {key:'Poços de Caldas', value:'Poços de Caldas'},
    {key:'Pomerode', value:'Pomerode'},
    {key:'Ponta Grossa', value:'Ponta Grossa'},
    {key:'Porto Alegre', value:'Porto Alegre'},
    {key:'Porto Feliz', value:'Porto Feliz'},
    {key:'Porto Seguro', value:'Porto Seguro'},
    {key:'Porto União', value:'Porto União'},
    {key:'Porto Velho', value:'Porto Velho'},
    {key:'Presidente Getúlio', value:'Presidente Getúlio'},
    {key:'Presidente Prudente', value:'Presidente Prudente'},
    {key:'Quaraí', value:'Quaraí'},
    {key:'Rancho Queimado', value:'Rancho Queimado'},
    {key:'Recife', value:'Recife'},
    {key:'Resende', value:'Resende'},
    {key:'Riacho das Almas', value:'Riacho das Almas'},
    {key:'Ribeirão Claro', value:'Ribeirão Claro'},
    {key:'Ribeirão Preto', value:'Ribeirão Preto'},
    {key:'Rio de Janeiro', value:'Rio de Janeiro'},
    {key:'Rio do Sul', value:'Rio do Sul'},
    {key:'Rio Pomba', value:'Rio Pomba'},
    {key:'Rio Verde', value:'Rio Verde'},
    {key:'Riozinho', value:'Riozinho'},
    {key:'Rodeio', value:'Rodeio'},
    {key:'Salvador', value:'Salvador'},
    {key:'Santa Cruz do Sul', value:'Santa Cruz do Sul'},
    {key:'Santa Maria Madalena', value:'Santa Maria Madalena'},
    {key:'Santa Rita do Passa Quatro', value:'Santa Rita do Passa Quatro'},
    {key:'Santa Rita', value:'Santa Rita'},
    {key:'Santa Teresa', value:'Santa Teresa'},
    {key:'Santa Teresinha', value:'Santa Teresinha'},
    {key:'Santarém', value:'Santarém'},
    {key:'Santiago', value:'Santiago'},
    {key:'Santo Amaro das Brotas', value:'Santo Amaro das Brotas'},
    {key:'Santo Amaro', value:'Santo Amaro'},
    {key:'Santo André', value:'Santo André'},
    {key:'Santo Ângelo', value:'Santo Ângelo'},
    {key:'Santo Antônio da Patrulha', value:'Santo Antônio da Patrulha'},
    {key:'Santo Antônio do Itambé', value:'Santo Antônio do Itambé'},
    {key:'Santo Antônio do Monte', value:'Santo Antônio do Monte'},
    {key:'Santo Augusto', value:'Santo Augusto'},
    {key:'Santos', value:'Santos'},
    {key:'São Bento do Sul', value:'São Bento do Sul'},
    {key:'São Bernardo do Campo', value:'São Bernardo do Campo'},
    {key:'São Borja', value:'São Borja'},
    {key:'São Caitano', value:'São Caitano'},
    {key:'São Carlos', value:'São Carlos'},
    {key:'São Fidélis', value:'São Fidélis'},
    {key:'São Francisco de Paula', value:'São Francisco de Paula'},
    {key:'São Gabriel', value:'São Gabriel'},
    {key:'São Gonçalo do Sapucaí', value:'São Gonçalo do Sapucaí'},
    {key:'São Gonçalo', value:'São Gonçalo'},
    {key:'São Jerônimo', value:'São Jerônimo'},
    {key:'São João Batista', value:'São João Batista'},
    {key:'São João del Rei', value:'São João del Rei'},
    {key:'São João do Meriti', value:'São João do Meriti'},
    {key:'São João do Sabugi', value:'São João do Sabugi'},
    {key:'São José de Piranhas', value:'São José de Piranhas'},
    {key:'São José do Rio Pardo', value:'São José do Rio Pardo'},
    {key:'São José', value:'São José'},
    {key:'São Leopoldo', value:'São Leopoldo'},
    {key:'São Luís', value:'São Luís'},
    {key:'São Mateus', value:'São Mateus'},
    {key:'São Miguel do Oeste', value:'São Miguel do Oeste'},
    {key:'São Paulo', value:'São Paulo'},
    {key:'São Pedro da Aldeia', value:'São Pedro da Aldeia'},
    {key:'São Pedro', value:'São Pedro'},
    {key:'Sapiranga', value:'Sapiranga'},
    {key:'Saquarema', value:'Saquarema'},
    {key:'Senador Canedo', value:'Senador Canedo'},
    {key:'Sério', value:'Sério'},
    {key:'Serra de São Bento', value:'Serra de São Bento'},
    {key:'Serra do Mel', value:'Serra do Mel'},
    {key:'Serra Negra', value:'Serra Negra'},
    {key:'Sete Lagoas', value:'Sete Lagoas'},
    {key:'Sobral', value:'Sobral'},
    {key:'Sorocaba', value:'Sorocaba'},
    {key:'Taió', value:'Taió'},
    {key:'Tanabi', value:'Tanabi'},
    {key:'Tanquinho', value:'Tanquinho'},
    {key:'Taquaritinga do Norte', value:'Taquaritinga do Norte'},
    {key:'Taubaté', value:'Taubaté'},
    {key:'Teixeira', value:'Teixeira'},
    {key:'Teófilo Otoni', value:'Teófilo Otoni'},
    {key:'Teresina', value:'Teresina'},
    {key:'Teresópolis', value:'Teresópolis'},
    {key:'Teutônia', value:'Teutônia'},
    {key:'Tibagi', value:'Tibagi'},
    {key:'Timon', value:'Timon'},
    {key:'Toledo', value:'Toledo'},
    {key:'Torrinha', value:'Torrinha'},
    {key:'Três Rios', value:'Três Rios'},
    {key:'Triunfo', value:'Triunfo'},
    {key:'Turvo', value:'Turvo'},
    {key:'Ubá', value:'Ubá'},
    {key:'Uberaba', value:'Uberaba'},
    {key:'Uberlândia', value:'Uberlândia'},
    {key:'Uruguaiana', value:'Uruguaiana'},
    {key:'Urussanga', value:'Urussanga'},
    {key:'Valença', value:'Valença'},
    {key:'Valença', value:'Valença'},
    {key:'Valinhos', value:'Valinhos'},
    {key:'Vargem Alta', value:'Vargem Alta'},
    {key:'Varginha', value:'Varginha'},
    {key:'Várzea Grande', value:'Várzea Grande'},
    {key:'Vespasiano', value:'Vespasiano'},
    {key:'Viamão', value:'Viamão'},
    {key:'Viçosa do Ceará', value:'Viçosa do Ceará'},
    {key:'Viçosa', value:'Viçosa'},
    {key:'Videira', value:'Videira'},
    {key:'Vigia', value:'Vigia'},
    {key:'Vila Nova do Sul', value:'Vila Nova do Sul'},
    {key:'Vila Velha', value:'Vila Velha'},
    {key:'Visconde do Rio Branco', value:'Visconde do Rio Branco'},
    {key:'Vitória da Conquista', value:'Vitória da Conquista'},
    {key:'Vitória', value:'Vitória'},
    {key:'Vitorino', value:'Vitorino'},
    {key:'Volta Redonda', value:'Volta Redonda'},
    {key:'Votorantim', value:'Votorantim'},
    {key:'Votuporanga', value:'Votuporanga'},
    
   ];

  
  return (
    <SafeAreaView style={styles.container}>
      <ScrollView>
        <View>
          <Text style={styles.title}>Repetidoras Brasil</Text>
          <SelecionarCidade setCidade={setCidade} cidades={cidades} />
          <DisplayRepetidoras pais="Brazil" cidade={cidade}></DisplayRepetidoras>
          <Text style={estilo.txtPProdape}>Fonte: https://www.repeaterbook.com</Text>
        </View>
      </ScrollView>

    </SafeAreaView>
  );
}



const styles = StyleSheet.create({
  container: {
    backgroundColor: '#902024',
    flexGrow: 1,
    justifyContent: "center",
    padding: 20,
  },
  title: {
    fontSize: 30,
    marginVertical: 50,
    borderWidth: 2,
    borderColor: "black",
    borderRadius:10,
    backgroundColor: 'yellow',
    color: "black",
    textAlign: "center",
    fontWeight: "bold",
  },
});

//export default ConsultaRep